package ihe.qrph.dex._2013;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * SOAP Web Service for IHE Data Element Exchange Profile
 *
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-31T17:14:40.958+03:00
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "DataElementExchangeService", 
                  wsdlLocation = "file:/C:/Users/AliAnil/SRDC/projects/salus/implementation/salus-project/common/semantic-mdr/dex/src/main/resources/DEX.wsdl",
                  targetNamespace = "urn:ihe:qrph:dex:2013") 
public class DataElementExchangeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:ihe:qrph:dex:2013", "DataElementExchangeService");
    public final static QName DataElementExchangePort = new QName("urn:ihe:qrph:dex:2013", "DataElementExchangePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/AliAnil/SRDC/projects/salus/implementation/salus-project/common/semantic-mdr/dex/src/main/resources/DEX.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DataElementExchangeService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/AliAnil/SRDC/projects/salus/implementation/salus-project/common/semantic-mdr/dex/src/main/resources/DEX.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DataElementExchangeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DataElementExchangeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataElementExchangeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DataElementExchangeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DataElementExchangeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DataElementExchangeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DataElementExchangePortType
     */
    @WebEndpoint(name = "DataElementExchangePort")
    public DataElementExchangePortType getDataElementExchangePort() {
        return super.getPort(DataElementExchangePort, DataElementExchangePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataElementExchangePortType
     */
    @WebEndpoint(name = "DataElementExchangePort")
    public DataElementExchangePortType getDataElementExchangePort(WebServiceFeature... features) {
        return super.getPort(DataElementExchangePort, DataElementExchangePortType.class, features);
    }

}
